name: Create GitHub Release with S3 Toolchain Info

on:
  workflow_dispatch:
    inputs:
      s3_toolchain_url:
        description: 'Direct S3 URL to the toolchain archive (.tar.gz or .zip)'
        required: true
        default: 'YOUR_DEFAULT_S3_TOOLCHAIN_URL'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Get timestamp
        id: datetime
        run: |
          echo "timestamp=$(date +%Y%m%d%H%M%S)" >> "$GITHUB_OUTPUT"
          echo "shortdate=$(date +%Y%m%d)" >> "$GITHUB_OUTPUT"

      - name: Download and Extract Toolchain, Get Clang/Binutils Info
        id: get_toolchain_info
        run: |
          set -euo pipefail

          S3_TOOLCHAIN_URL="${{ github.event.inputs.s3_toolchain_url }}"
          DOWNLOAD_DIR="downloaded_toolchain"
          EXTRACTED_PATH="$DOWNLOAD_DIR/extracted_clang"

          mkdir -p "$DOWNLOAD_DIR"
          FILENAME=$(basename "$S3_TOOLCHAIN_URL")
          DOWNLOAD_PATH="$DOWNLOAD_DIR/$FILENAME"

          echo "Downloading toolchain from: $S3_TOOLCHAIN_URL"
          curl -L -o "$DOWNLOAD_PATH" "$S3_TOOLCHAIN_URL"
          echo "Downloaded to: $DOWNLOAD_PATH"

          mkdir -p "$EXTRACTED_PATH"
          if [[ "$FILENAME" == *.tar.gz ]]; then
            tar -xzf "$DOWNLOAD_PATH" -C "$EXTRACTED_PATH"
          elif [[ "$FILENAME" == *.zip ]]; then
            unzip "$DOWNLOAD_PATH" -d "$EXTRACTED_PATH"
          else
            echo "Unsupported archive format"
            exit 1
          fi

          CLANG_BINARY_PATH="$EXTRACTED_PATH/bin/clang"
          if [ ! -f "$CLANG_BINARY_PATH" ]; then
            echo "Clang binary not found"
            exit 1
          fi
          chmod +x "$CLANG_BINARY_PATH"

          CLANG_VERSION_OUTPUT=$("$CLANG_BINARY_PATH" --version)
          CLANG_VERSION_RAW=$(echo "$CLANG_VERSION_OUTPUT" | grep -oP 'clang version \K[^\s]+')
          CLANG_VERSION="${CLANG_VERSION_RAW:-N/A}"
          CLANG_VERSION_TAG_SAFE=$(echo "$CLANG_VERSION_RAW" | sed 's/[^a-zA-Z0-9._-]/_/g; s/+/-/g; s/^[-_]*//; s/[-_]*$//')

          [ -z "$CLANG_VERSION_TAG_SAFE" ] && CLANG_VERSION_TAG_SAFE="unknown"

          LLVM_COMMIT_HASH=$(echo "$CLANG_VERSION_OUTPUT" | grep -oP '\(https:\/\/github\.com\/llvm\/llvm-project\s+\K[a-f0-9]{40}' || echo "N/A")
          CLANG_BINARY_SHA256=$(sha256sum "$CLANG_BINARY_PATH" | awk '{print $1}')

          LD_BINARY_PATH="$EXTRACTED_PATH/bin/ld"
          BINUTILS_VERSION="N/A"
          if [ -x "$LD_BINARY_PATH" ]; then
            BINUTILS_VERSION_OUTPUT=$("$LD_BINARY_PATH" --version 2>&1 || true)
            BINUTILS_VERSION=$(echo "$BINUTILS_VERSION_OUTPUT" | grep -oP 'GNU ld \(GNU Binutils\) \K\d+(\.\d+)+')
          fi

          echo "CLANG_VERSION=$CLANG_VERSION" >> "$GITHUB_OUTPUT"
          echo "CLANG_VERSION_TAG_SAFE=$CLANG_VERSION_TAG_SAFE" >> "$GITHUB_OUTPUT"
          echo "LLVM_COMMIT_HASH=$LLVM_COMMIT_HASH" >> "$GITHUB_OUTPUT"
          echo "CLANG_BINARY_SHA256=$CLANG_BINARY_SHA256" >> "$GITHUB_OUTPUT"
          echo "BINUTILS_VERSION=$BINUTILS_VERSION" >> "$GITHUB_OUTPUT"

      - name: Check if GitHub Release Already Exists
        id: check_release
        run: |
          set -euo pipefail
          TAG="v${{ steps.get_toolchain_info.outputs.CLANG_VERSION_TAG_SAFE }}-${{ steps.datetime.outputs.shortdate }}"
          echo "release_tag=$TAG" >> "$GITHUB_OUTPUT"

          response=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Authorization: Bearer ${{ secrets.ABISMO_DE_LOS_SECRETOS }}" \
            "https://api.github.com/repos/${{ github.repository }}/releases/tags/$TAG")

          if [ "$response" = "200" ]; then
            echo "exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "exists=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Create GitHub Release (if not exists)
        if: steps.check_release.outputs.exists == 'false'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ABISMO_DE_LOS_SECRETOS }}
        with:
          tag_name: "${{ steps.check_release.outputs.release_tag }}"
          release_name: "Yuki ユキ+bolt clang update V${{ steps.get_toolchain_info.outputs.CLANG_VERSION }} ${{ steps.datetime.outputs.shortdate }}"
          body: |
            ## Toolchain Info

            - LLVM version: ${{ steps.get_toolchain_info.outputs.CLANG_VERSION }}
            - Binutils version: ${{ steps.get_toolchain_info.outputs.BINUTILS_VERSION }}
            - LLVM commit: `${{ steps.get_toolchain_info.outputs.LLVM_COMMIT_HASH }}`
            - SHA256 of clang binary: `${{ steps.get_toolchain_info.outputs.CLANG_BINARY_SHA256 }}`

            ---
            _This release was created via GitHub Actions, downloading the toolchain from S3._
          draft: false
          prerelease: false

      - name: Upload release asset (.tar.gz) if not already uploaded
        env:
          GITHUB_TOKEN: ${{ secrets.ABISMO_DE_LOS_SECRETOS }}
          REPO: ${{ github.repository }}
          TAG: ${{ steps.check_release.outputs.release_tag }}
        run: |
          set -euo pipefail
          ASSET_PATH=$(echo downloaded_toolchain/*.tar.gz)
          ASSET_NAME=$(basename "$ASSET_PATH")

          echo "Getting release ID for tag $TAG"
          RELEASE_ID=$(curl -s \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/$REPO/releases/tags/$TAG" | jq -r '.id')

          if [ -z "$RELEASE_ID" ] || [ "$RELEASE_ID" = "null" ]; then
            echo "Error: Release ID not found for tag $TAG"
            exit 1
          fi

          echo "Checking if asset $ASSET_NAME already uploaded..."
          ASSET_EXISTS=$(curl -s \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/$REPO/releases/$RELEASE_ID/assets" | jq -r --arg NAME "$ASSET_NAME" '.[] | select(.name == $NAME) | .name')

          if [ "$ASSET_EXISTS" = "$ASSET_NAME" ]; then
            echo "Asset $ASSET_NAME already uploaded, skipping upload."
            exit 0
          fi

          echo "Uploading asset $ASSET_NAME ..."
          curl --fail -X POST \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Content-Type: application/gzip" \
            --data-binary @"$ASSET_PATH" \
            "https://uploads.github.com/repos/$REPO/releases/$RELEASE_ID/assets?name=$ASSET_NAME"

          echo "Upload finished."
